#!/bin/bash

#SBATCH --job-name=macsyfinder_concat
#SBATCH --account=xx
#SBATCH --time=05:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G

set -o errexit # Exit the script on any error
set -o nounset # Treat any unset variable as an error

echo "Usage: macsyfinder_concat.sh"

# Copy and rename all best_solution.tsv files
mkdir output/IDx/best_solution
for file in output/IDx/*/best_solution.tsv;
do
        OUT=$(echo $file | cut -d / -f 3);
        END=_best_solution.tsv;
        OUTFILE=${OUT}${END};
        cp $file output/IDx/best_solution/$OUTFILE;
done

# copy and rename all best_solution_summary.tsv files
mkdir output/IDx/best_solution_summary
for file in output/IDx/*/best_solution_summary.tsv;
do
        OUT=$(echo $file | cut -d / -f 3);
        END=_best_solution_summary.tsv;
        OUTFILE=${OUT}${END};
        cp $file output/IDx/best_solution_summary/$OUTFILE;
done

echo "finished"
